// Sliding Window — smallest subarray with sum >= target.
//
// The trace is GENERATED by running the real two-pointer algorithm and
// snapshotting state at every transition. Nothing here is hand-authored frame
// data: change the algorithm and the animation changes with it.

import type { Problem, VarBinding, WalkStep } from "./types";

const C = {
  window: "var(--teal)",
  right: "var(--blue)",
  left: "var(--purple)",
  sum: "var(--amber)",
  min: "var(--green)",
};

const INF = "∞";

// Code lines. codeLine on each step indexes into this array.
const CODE = [
  "def smallest_window(nums, target):",
  "    left = 0",
  "    current_sum = 0",
  "    min_len = infinity",
  "    for right in range(len(nums)):",
  "        current_sum += nums[right]",
  "        while current_sum >= target:",
  "            min_len = min(min_len, right - left + 1)",
  "            current_sum -= nums[left]",
  "            left += 1",
  "    return min_len",
];

interface Ctx {
  left: number;
  right: number; // -1 before the loop starts
  sum: number;
  minLen: number | null; // null => still infinity
}

function fmt(n: number): string {
  return String(n);
}

/** Build the variable-board bindings for the current context. */
function vars(ctx: Ctx, changed: Partial<Record<"left" | "right" | "sum" | "min", boolean>> = {}): VarBinding[] {
  return [
    { name: "left", value: fmt(ctx.left), color: C.left, changed: changed.left },
    { name: "right", value: ctx.right < 0 ? "—" : fmt(ctx.right), color: C.right, changed: changed.right },
    { name: "current_sum", value: fmt(ctx.sum), color: C.sum, changed: changed.sum },
    {
      name: "min_len",
      value: ctx.minLen === null ? INF : fmt(ctx.minLen),
      color: C.min,
      changed: changed.min,
    },
  ];
}

export function buildSlidingWindow(
  nums: number[] = [2, 1, 5, 2, 3, 2],
  target: number = 7
): WalkStep[] {
  const steps: WalkStep[] = [];
  const ctx: Ctx = { left: 0, right: -1, sum: 0, minLen: null };

  const push = (
    partial: Omit<WalkStep, "viz" | "vars"> & {
      flash?: number[];
      changed?: Partial<Record<"left" | "right" | "sum" | "min", boolean>>;
      showWindow?: boolean;
    }
  ) => {
    const { flash = [], changed, showWindow = true, ...rest } = partial;
    // A window only exists once right has entered the array and left <= right.
    const hasWindow = showWindow && ctx.right >= 0 && ctx.left <= ctx.right;
    const markers = [
      { index: ctx.left, label: "left", color: C.left, above: false },
      ...(ctx.right >= 0 ? [{ index: ctx.right, label: "right", color: C.right, above: true }] : []),
    ];
    steps.push({
      ...rest,
      viz: {
        kind: "array",
        values: nums,
        markers,
        window: hasWindow
          ? {
              start: ctx.left,
              end: ctx.right,
              color: C.window,
              label: `size ${ctx.right - ctx.left + 1}`,
            }
          : null,
        flash,
      },
      vars: vars(ctx, changed),
    });
  };

  // --- Setup -------------------------------------------------------------
  push({
    phase: "Setup",
    codeLine: 1,
    narration:
      "We start with a window that has no width yet. left marks the start of the window and sits at index 0.",
    changed: { left: true },
    showWindow: false,
  });
  push({
    phase: "Setup",
    codeLine: 2,
    narration:
      "current_sum will hold the total of the numbers inside the window. It begins at 0 because the window is empty.",
    changed: { sum: true },
    showWindow: false,
  });
  push({
    phase: "Setup",
    codeLine: 3,
    narration:
      "min_len is the smallest window we have found so far. We set it to infinity so that any real window will look smaller.",
    changed: { min: true },
    showWindow: false,
  });

  // --- Main loop ---------------------------------------------------------
  for (let right = 0; right < nums.length; right++) {
    ctx.right = right;
    push({
      phase: "Expand",
      codeLine: 4,
      narration: `right moves to index ${right}. We are about to pull the value ${nums[right]} into the window.`,
      changed: { right: true },
      flash: [right],
    });

    ctx.sum += nums[right];
    push({
      phase: "Expand",
      codeLine: 5,
      narration: `Add nums[${right}] = ${nums[right]} to current_sum. The window now holds ${ctx.sum}.`,
      changed: { sum: true },
      flash: [right],
    });

    // Shrink while the window is valid.
    // eslint-disable-next-line no-constant-condition
    while (true) {
      const qualifies = ctx.sum >= target;
      push({
        phase: "Check",
        codeLine: 6,
        narration: qualifies
          ? `Is current_sum (${ctx.sum}) ≥ target (${target})? Yes — this window is big enough. Try to shrink it from the left.`
          : `Is current_sum (${ctx.sum}) ≥ target (${target})? No — the window is too small. Let right grow to add more.`,
      });
      if (!qualifies) break;

      const size = ctx.right - ctx.left + 1;
      const isBetter = ctx.minLen === null || size < ctx.minLen;
      const prevMin = ctx.minLen;
      if (isBetter) ctx.minLen = size;
      push({
        phase: "Record",
        codeLine: 7,
        narration: isBetter
          ? `This window is length ${size}${prevMin === null ? "" : `, smaller than ${prevMin}`}. Record it as the new best min_len.`
          : `This window is length ${size}, but min_len is already ${prevMin}. Keep the old best.`,
        changed: { min: isBetter },
        flash: [],
      });

      const removed = nums[ctx.left];
      ctx.sum -= removed;
      push({
        phase: "Shrink",
        codeLine: 8,
        narration: `Shrink from the left: remove nums[${ctx.left}] = ${removed}. current_sum drops to ${ctx.sum}.`,
        changed: { sum: true },
        flash: [ctx.left],
      });

      ctx.left += 1;
      push({
        phase: "Shrink",
        codeLine: 9,
        narration: `Move left forward to index ${ctx.left}. The window is now narrower.`,
        changed: { left: true },
      });
    }
  }

  // --- Return ------------------------------------------------------------
  ctx.right = nums.length - 1;
  push({
    phase: "Done",
    codeLine: 10,
    narration:
      ctx.minLen === null
        ? "right reached the end and no window ever met the target. The answer is infinity — no valid window exists."
        : `right reached the end. The smallest window that meets the target has length ${ctx.minLen}. That is our answer.`,
    changed: { min: true },
    showWindow: false,
  });

  return steps;
}

export const slidingWindowProblem: Problem = {
  slug: "smallest-subarray-sum",
  title: "Smallest Subarray with Sum ≥ Target",
  emoji: "🪟",
  iconClass: "teal",
  tags: ["Sliding Window", "Two Pointers", "Arrays"],
  difficulty: "medium",
  oneLiner:
    "Find the shortest run of neighbouring numbers that adds up to at least the target.",
  intuition:
    "Think of a window you slide across the numbers. Grow it on the right until the total is big enough, then squeeze it from the left to make it as small as possible. The window never goes backwards, so you touch each number at most twice.",
  statement:
    "You are given a list of positive numbers and a target.\n\nFind the length of the shortest contiguous block (a run of side-by-side numbers) whose sum is greater than or equal to the target.\n\nIf no block reaches the target, the answer is infinity — there is no valid window.",
  examples: [
    {
      input: "nums = [2, 1, 5, 2, 3, 2], target = 7",
      output: "2",
      why: "The block [5, 2] adds up to 7 and has length 2. No single number reaches 7, so 2 is the shortest.",
    },
    {
      input: "nums = [3, 4, 1, 1, 6], target = 6",
      output: "1",
      why: "The single number 6 already meets the target, so the shortest window has length 1.",
    },
    {
      input: "nums = [1, 1, 1], target = 9",
      output: "infinity",
      why: "Even the whole list only sums to 3, so no window ever reaches 9.",
    },
  ],
  language: "Python",
  code: CODE,
  complexity: {
    time: "O(n)",
    space: "O(1)",
    note: "left and right each only move forward, so every number is added once and removed at most once — one pass, not a nested scan.",
  },
  build: () => buildSlidingWindow([2, 1, 5, 2, 3, 2], 7),
  connectsTo:
    "The two-pointer window here is the same trick behind 'longest substring without repeats' and many string problems. Looking back, it beats the slow O(n²) way of checking every block — the same speed jump you saw going from linear search to binary search.",
};
